[package]
name = "render-template"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.6"
minijinja = { path = "../../minijinja" }
serde_json = "1.0.68"
