[package]
name = "minijinja-py"
version = "3.0.0-alpha.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "minijinja_py"
crate-type = ["cdylib"]

[dependencies]
minijinja = { version = "3.0.0-alpha.3", path = "../minijinja", features = ["json", "urlencode", "fuel", "preserve_order", "speedups", "loop_controls", "unicode", "internal_safe_search"] }
minijinja-contrib = { version = "3.0.0-alpha.3", path = "../minijinja-contrib", features = ["pycompat", "html_entities", "wordwrap"] }
pyo3 = { version = "0.29.3", features = ["abi3-py310"] }
