[package]
name = "minijinja-py"
version = "3.0.0-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "minijinja_py"
crate-type = ["cdylib"]

[dependencies]
minijinja = { version = "3.0.0-alpha.0", path = "../minijinja", features = ["json", "urlencode", "fuel", "preserve_order", "speedups", "custom_syntax", "loop_controls", "unicode", "internal_safe_search"] }
minijinja-contrib = { version = "3.0.0-alpha.0", path = "../minijinja-contrib", features = ["pycompat", "html_entities", "wordwrap"] }
pyo3 = { version = "0.27.0", features = ["extension-module", "abi3-py38"] }

[build-dependencies]
pyo3-build-config = "0.27.0"
