[package]
name = "minijinja-dis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.8"
minijinja = { path = "../../minijinja", features = ["unstable_machinery", "custom_syntax"] }
