[package]
name = "stack-ref"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minijinja = { path = "../../minijinja" }
minijinja-stack-ref = { path = "../../minijinja-stack-ref" }
