[package]
name = "minijinja-cli"
version = "3.0.0-alpha.2"
edition = "2021"
license = "Apache-2.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "Command Line Utility to render MiniJinja/Jinja2 templates"
homepage = "https://github.com/mitsuhiko/minijinja"
repository = "https://github.com/mitsuhiko/minijinja"
keywords = ["jinja", "jinja2", "templates", "cli"]
readme = "README.md"
rust-version = "1.88"

[features]
default = ["toml", "yaml", "querystring", "cbor", "datetime", "json5", "repl", "completions", "unicode", "ini", "contrib", "preserve_order"]
yaml = ["dep:deser-yaml"]
querystring = []
cbor = ["dep:deser-cbor"]
datetime = ["minijinja-contrib/datetime", "minijinja-contrib/timezone"]
json5 = ["dep:deser-json5"]
repl = ["rustyline"]
completions = ["argument-completions"]
unicode = ["minijinja/unicode"]
ini = ["dep:deser-ini"]
contrib = ["minijinja-contrib", "minijinja-contrib/html_entities"]
toml = ["dep:deser-toml"]
preserve_order = ["minijinja/preserve_order"]

[dependencies]
anyhow = "1.0.74"
argument = "0.1.0"
argument-completions = { version = "0.1.0", optional = true }
minijinja = { version = "=3.0.0-alpha.2", path = "../minijinja", features = [
    "json",
    "urlencode",
    "fuel",
    "unstable_machinery",
    "custom_syntax",
    "loop_controls"
] }
minijinja-contrib = { version = "=3.0.0-alpha.2", optional = true, path = "../minijinja-contrib", features = ["pycompat", "datetime", "timezone", "rand", "unicode_wordwrap", "wordcount"] }
rustyline = { version = "14.0.0", optional = true, default-features = false }
deser = { version = "0.10.0", features = ["derive"] }
deser-cbor = { version = "0.10.0", optional = true }
deser-ini = { version = "0.10.0", optional = true }
deser-json = "0.10.0"
deser-json5 = { version = "0.10.0", optional = true }
deser-toml = { version = "0.10.0", optional = true }
deser-value = "0.10.0"
deser-yaml = { version = "0.10.0", optional = true }

[target.'cfg(windows)'.dependencies]
dunce = "1.0.4"

[build-dependencies]
argument = "0.1.0"
argument-completions = { version = "0.1.0", optional = true }
argument-mangen = "0.1.0"

[dev-dependencies]
insta = { version = "1.38.0", features = ["filters"] }
insta-cmd = "0.6.0"
tempfile = "3.9.0"
