[package]
name = "minijinja-py"
version = "1.0.16"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "minijinja_py"
crate-type = ["cdylib"]

[dependencies]
minijinja = { version = "1.0.16", path = "../minijinja", features = ["loader", "json", "urlencode", "fuel", "preserve_order", "speedups", "custom_syntax"] }
once_cell = "1.17.0"
pyo3 = { version = "0.18.0", features = ["extension-module", "serde", "abi3-py38"] }
