name: Pyright

on: [push, pull_request]

jobs:
  pyright:
    name: Pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run pyright
        run: make python-type-check
